### ISSUE TITLE
Pumpkin spice latte asks for ctd core 1.2

### ISSUE THREAD

**Issue by beesyndicate** [MasterGeneral156/Pumpkin-Spice-Latte#1]
server crashes on startup b/c it says that pumpkin spice latte requires ctd core 1.2 and it dosnt seem like that is available 

[11:46:53] [Server thread/FATAL] [FML]: The mod pumpkinspice (Pumpkin Spice Latte) requires mods [ctdcore] to be available
[11:46:53] [Server thread/FATAL] [FML]: Mod pumpkinspice (Pumpkin Spice Latte) requires [ctdcore@[1.2,]]
[11:46:53] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod pumpkinspice (Pumpkin Spice Latte) requires [ctdcore@[1.2,]]
Missing Mods:
	ctdcore : [1.2,]

	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:258) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[11:46:53] [Server thread/ERROR]: This crash report has been saved to: /home/tf/forest test/./crash-reports/crash-2017-10-19_11.46.53-server.txt
[11:46:53] [Server thread/INFO]: Stopping server
[11:46:53] [Server thread/INFO]: Saving worlds
[11:46:53] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[11:46:53] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[11:46:53] [Server Shutdown Thread/INFO]: Stopping server
[11:46:53] [Server Shutdown Thread/INFO]: Saving worlds
> tf@tf-HP-Compaq-6000-Pro-SFF-PC:~/forest test$

**Comment by MasterGeneral156** [comment]
You've downloaded [CTD Core](https://minecraft.curseforge.com/projects/ctd-core) right?

**Comment by beesyndicate** [comment]
yep tried both 1.11.2 and 1.12.1

**Comment by beesyndicate** [comment]
NM got it 1.12.2 works the log is a bit misleading

**Comment by MasterGeneral156** [comment]
Was about to tell you its working for me lol. Glad you figured it out.

**Comment by beesyndicate** [comment]
thank you for your help have a great day sorry for the interruption
